using System;
using System.Collections.Generic;

namespace OpenVR.NET.Manifests {
	/// <summary>
	/// A manifest of how controller buttons and such should be renamed into enum values.
	/// </summary>
	public class Manifest<TGroup, TAction> : Manifest where TAction : Enum where TGroup : Enum {
		public List<ActionGroup<TGroup, TAction>> Groups = new();

		public override IEnumerable<ActionGroup> EnumerateGroups ()
			=> Groups;
	}

	/// <summary>
	/// Base type of <see cref="Manifest{TGroup, TAction}"/> as Enums are not covariant. Don't use this.
	/// </summary>
	public abstract class Manifest {
		public abstract IEnumerable<ActionGroup> EnumerateGroups ();
		public List<DefaultBinding> DefaultBindings = new();
		/// <summary>
		/// A unique name to identify the program. Should be in the style of myCompany.myProjectName to avoid collisions
		/// </summary>
		public string Name;
		public LaunchType LaunchType;
		/// <summary>
		/// The path to the binary. If not set, will be determined automatically based on the entry assembly location.
		/// </summary>
		public string Path;
		public bool IsDashBoardOverlay;
		// ActionsManifestPath is autogenerated
		/// <summary>
		/// Locale names. The key should follow http://www.lingoes.net/en/translator/langcode.htm (but lowercase snake case).
		/// </summary>
		public List<ManifestLocale> Localizations = new();
	}

	public enum LaunchType {
		Binary
	}

	public struct ManifestLocale {
		public string LanguageTag;

		public ManifestLocale ( string languageTag ) : this() {
			LanguageTag = languageTag;
		}

		public string Name;
		public string Description;
	}
}
